-- 006_morning_briefings.sql
-- Creates the morning_briefings table used by premarket_briefing.py
-- to persist the daily AI-generated pre-market analysis.

create table if not exists morning_briefings (
    id              bigserial primary key,
    briefing_text   text            not null,
    top_movers      jsonb           not null default '[]'::jsonb,
    regime_snapshot jsonb           not null default '{}'::jsonb,
    generated_at    timestamptz     not null,
    created_at      timestamptz     not null default now()
);

-- Index for fast retrieval of the latest briefing
create index if not exists morning_briefings_generated_at_idx
    on morning_briefings (generated_at desc);

alter table morning_briefings enable row level security;

drop policy if exists "service role all" on morning_briefings;
create policy "service role all" on morning_briefings
    for all using (auth.role() = 'service_role');

drop policy if exists "anon read" on morning_briefings;
create policy "anon read" on morning_briefings
    for select using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'morning_briefings'
  ) then
    alter publication supabase_realtime add table morning_briefings;
  end if;
end;
$$;

-- Optional: keep only the last 90 days of briefings
comment on table morning_briefings is
    'Daily AI pre-market briefings generated by premarket_briefing.py at 8 AM ET.';

comment on column morning_briefings.briefing_text is
    '3-paragraph narrative from Claude: market read, top setups, risks to avoid.';

comment on column morning_briefings.top_movers is
    'JSON array of {symbol, gap_pct, premarket_vol} sorted by absolute gap size.';

comment on column morning_briefings.regime_snapshot is
    'Full regime dict from get_full_regime() at the time of generation.';

comment on column morning_briefings.generated_at is
    'UTC timestamp when the briefing was generated (before market open).';
